[font]
size = 12.0
normal = {family = "NotoSans Mono"}

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "E"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "Y"
mode = "~Alt"
mods = "Control"

[colors.primary]
background = "#1e1e1e"
